{% set name = "compas_viewer" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7810758069420f61f54b5e7d295a813e29c04ef05c1f183208bed3854ed30d97

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - compas >=2.2
    - freetype-py
    - pyopengl
    - pyside6

test:
  imports:
    - compas_viewer

about:
  home: https://compas.dev/compas_viewer/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Viewer for COMPAS 2 based on PyOpenGL and PyQt6.'
  doc_url: http://compas.dev/compas_viewer/
  dev_url: https://github.com/compas-dev/compas_viewer

extra:
  recipe-maintainers:
    - tomvanmele
    - Licini
